### ISSUE TITLE
本地部署问题

### ISSUE THREAD

**Issue by silence-pan84** [AIDotNet/auto-prompt#11]
本地部署使用的是sqlite并且使用的本地模型本机访问正常，其它电脑访问并注册账号登录后工作台的模型配置并不是本地部署的配置。

**Comment by 239573049** [comment]
是否通过环境变量配置模型列表？如果有查看f12网络请求

**Comment by 239573049** [comment]
> > 是否通过环境变量配置模型列表？如果有查看f12网络请求
> 
> 通过appsettings.json配置的模型列表

使用docker部署还是什么？

**Comment by silence-pan84** [comment]
> > > 是否通过环境变量配置模型列表？如果有查看f12网络请求
> > 
> > 
> > 通过appsettings.json配置的模型列表
> 
> 使用docker部署还是什么？

docker部署的

**Comment by 239573049** [comment]
docker部署你应该修改环境变量

**Comment by 239573049** [comment]
这个错误最新版已经修复，你应该没更新镜像

**Comment by silence-pan84** [comment]
> 这个错误最新版已经修复，你应该没更新镜像

更新最近的镜像还是有这个错误，模型列表中的模型到是少了几个。

**Comment by silence-pan84** [comment]
> 这个错误最新版已经修复，你应该没更新镜像

更新最新的镜像还是有这个错误，模型列表中的模型到是少了几个。

![Image](https://github.com/user-attachments/assets/46e59151-44f9-4ff9-94ad-69fb91c53859)

**Comment by silence-pan84** [comment]
远端访问加载的模型列表


本地访问加载的模型列表

![Image](https://github.com/user-attachments/assets/39fbe839-9492-4894-a064-6f14c1409e97)

**Comment by silence-pan84** [comment]
远端访问加载的模型列表

![Image](https://github.com/user-attachments/assets/0bd50755-c30a-4eeb-b298-4168a7c5ff3e)
本地访问加载的模型列表

![Image](https://github.com/user-attachments/assets/adbda384-2545-43dc-8e8e-7796912431ac)

**Comment by 239573049** [comment]
这个列表只会读取您的本地配置的模型列表，如果出现图1的模型列表则说明模型列表读取失败了

**Comment by silence-pan84** [comment]
> 这个列表只会读取您的本地配置的模型列表，如果出现图1的模型列表则说明模型列表读取失败了
本地访问加载正常，换台电脑访问就加载失败了？而且更新到最新的镜像还报这个错误。

![Image](https://github.com/user-attachments/assets/4c0b847c-abee-4591-b5a3-c73a63958efd)

**Comment by silence-pan84** [comment]
模型列表的问题已经解决了，但是还报

![Image](https://github.com/user-attachments/assets/38dcf3fe-2a1c-41b1-a267-19b0b6838925)

**Comment by 239573049** [comment]
你的镜像是不是最新版

**Comment by silence-pan84** [comment]
> 你的镜像是不是最新版

![Image](https://github.com/user-attachments/assets/fd682935-9f13-4309-9b91-461e79adaed4)
这个版本应该是最新的吧

**Comment by 239573049** [comment]
后台是否有日志？

**Comment by 239573049** [comment]
日志并没有看到错误，我可能需要在加详细日志

**Comment by YiQing-Songs** [comment]
我也有这个问题，我是通过docker配的本地部署的LLM（非ollama）容器内可以连通api，但auto-prompt下拉模型列表里找不到我本地的模型，我还缺少了什么地方的配置吗难道？

![Image](https://github.com/user-attachments/assets/483a4d86-09c2-44d9-86ec-128b65b32d99)

以及重拉了很多遍新的镜像文件也还是有右边这个错误提示

![Image](https://github.com/user-attachments/assets/02cd44bd-7881-4d8a-8778-1881a287c2ed)

**Comment by 239573049** [comment]
我发现了问题，新版本的compose文件映射目录不是 ./data:/data

﻿services:
  console-service:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/console
    ports:
      - 10426:8080
    environment:
      - TZ=Asia/Shanghai
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin123
    volumes:
      - ./data:/app/data
    build:
      context: .
      dockerfile: src/Console.Service/Dockerfile

**Comment by YiQing-Songs** [comment]
还有白色界面的情况下这两个功能框的效果不太好

![Image](https://github.com/user-attachments/assets/a51c4149-b573-4ba3-ad0c-a5ff5e15e4da)

**Comment by YiQing-Songs** [comment]
> 我发现了问题，新版本的compose文件映射目录不是 ./data：/data
> 
> 服务： console-service： 映像： registry.cn-shenzhen.aliyuncs.com/tokengo/console 端口： - 10426：8080 环境： - TZ=亚洲/上海 - DEFAULT_USERNAME=admin - DEFAULT_PASSWORD=admin123 卷： - ./data：/app/data build： context： . dockerfile：src/Console.Service/Dockerfile

是的 这个是根据旧版的来配置的 您旧版存在这个路径的问题，新版我已经重新配置了 仍然没有我的本地模型

**Comment by silence-pan84** [comment]
> 我发现了问题，新版本的compose文件映射目录不是 ./data:/data
> 
> ﻿services: console-service: image: registry.cn-shenzhen.aliyuncs.com/tokengo/console ports: - 10426:8080 environment: - TZ=Asia/Shanghai - DEFAULT_USERNAME=admin - DEFAULT_PASSWORD=admin123 volumes: - ./data:/app/data build: context: . dockerfile: src/Console.Service/Dockerfile

![Image](https://github.com/user-attachments/assets/e8b3aa27-2a11-4177-9ad3-a3147af85377)

**Comment by 239573049** [comment]
> > 我发现了问题，新版本的compose文件映射目录不是 ./data:/data
> > ﻿services: console-service: image: registry.cn-shenzhen.aliyuncs.com/tokengo/console ports: - 10426:8080 environment: - TZ=Asia/Shanghai - DEFAULT_USERNAME=admin - DEFAULT_PASSWORD=admin123 volumes: - ./data:/app/data build: context: . dockerfile: src/Console.Service/Dockerfile
> 
> ![Image](https://github.com/user-attachments/assets/e8b3aa27-2a11-4177-9ad3-a3147af85377)

看来我得更新一下配置，你可以试试看能不能解决

**Comment by YiQing-Songs** [comment]
> 本地部署使用的是sqlite并且使用的本地模型本机访问正常，其它电脑访问并注册账号登录后工作台的模型配置并不是本地部署的配置。

能问下这个问题您怎么解决的吗？我的问题也类似于这个模型配置

**Comment by 239573049** [comment]
> > 本地部署使用的是sqlite并且使用的本地模型本机访问正常，其它电脑访问并注册账号登录后工作台的模型配置并不是本地部署的配置。
> 
> 能问下这个问题您怎么解决的吗？我的问题也类似于这个模型配置

尝试上面的方法，修改映射目录

**Comment by 239573049** [comment]
> > 我发现了问题，新版本的compose文件映射目录不是 ./data:/data
> > ﻿services: console-service: image: registry.cn-shenzhen.aliyuncs.com/tokengo/console ports: - 10426:8080 environment: - TZ=Asia/Shanghai - DEFAULT_USERNAME=admin - DEFAULT_PASSWORD=admin123 volumes: - ./data:/app/data build: context: . dockerfile: src/Console.Service/Dockerfile
> 
> ![Image](https://github.com/user-attachments/assets/e8b3aa27-2a11-4177-9ad3-a3147af85377)

新版本应该是更新了的，

**Comment by 239573049** [comment]
![Image](https://github.com/user-attachments/assets/6ffce3fc-c06e-46db-83f2-c5b368088b46)
请更新映射的目录配置，改成  ./data:/app/data

**Comment by silence-pan84** [comment]
> ![Image](https://github.com/user-attachments/assets/6ffce3fc-c06e-46db-83f2-c5b368088b46) 请更新映射的目录配置，改成 ./data:/app/data

![Image](https://github.com/user-attachments/assets/9ae7f657-bc13-4695-b8a2-a1b7ead86b63)这块修改吗？

**Comment by 239573049** [comment]
services:
  console-service:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/console
    ports:
      - 10426:8080
    environment:
      - TZ=Asia/Shanghai
      - OpenAIEndpoint=https://your-custom-api.com/v1
      # AI Model Configuration
      - CHAT_MODEL=gpt-4,gpt-3.5-turbo,claude-3-sonnet
      - IMAGE_GENERATION_MODEL=dall-e-3,midjourney,stable-diffusion
      - DEFAULT_CHAT_MODEL=gpt-4
      - DEFAULT_IMAGE_GENERATION_MODEL=dall-e-3
      - GenerationChatModel=gpt-4
      # Database Configuration
      - ConnectionStrings:Type=sqlite
      - ConnectionStrings:Default=Data Source=/app/data/ConsoleService.db
    volumes:
      - ./data:/app/data
    build:
      context: .
      dockerfile: src/Console.Service/Dockerfile

**Comment by 239573049** [comment]
```
services:
  console-service:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/console
    ports:
      - 10426:8080
    environment:
      - TZ=Asia/Shanghai
      - OpenAIEndpoint=https://your-custom-api.com/v1
      # AI Model Configuration
      - CHAT_MODEL=gpt-4,gpt-3.5-turbo,claude-3-sonnet
      - IMAGE_GENERATION_MODEL=dall-e-3,midjourney,stable-diffusion
      - DEFAULT_CHAT_MODEL=gpt-4
      - DEFAULT_IMAGE_GENERATION_MODEL=dall-e-3
      - GenerationChatModel=gpt-4
      # Database Configuration
      - ConnectionStrings:Type=sqlite
      - ConnectionStrings:Default=Data Source=/data/ConsoleService.db
    volumes:
      - ./data:/app/data
    build:
      context: .
      dockerfile: src/Console.Service/Dockerfile
```
